<?php

/**
 * This file is part of the DebugPHP package.
 *
 * (c) Leon Schmidt <kontakt@callmeleon.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/CallMeLeon167/debugphp
 */

declare(strict_types=1);

namespace DebugPHP;

/**
 * Captures PHP errors, warnings, notices and deprecations and forwards them
 * to the DebugPHP dashboard as structured table entries.
 *
 * This class is not intended to be instantiated directly.
 * Use {@see Debug::captureErrors()} instead.
 *
 * Important notes:
 * - Does NOT call {@see error_reporting()} — the host application's reporting
 *   level is intentionally left untouched.
 * - The $levels bitmask only controls what DebugPHP forwards to the dashboard.
 * - If the host application already has a custom error handler registered,
 *   this class will replace it. The previous handler is NOT chained.
 */
final class ErrorCapture
{
    /**
     * PHP error types that are fatal and cannot be intercepted by set_error_handler().
     * These are only catchable via a shutdown function + error_get_last().
     *
     * @var list<int>
     */
    private const FATAL_TYPES = [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR];

    /**
     * Number of stack frames to show in the trace section.
     *
     * @var int
     */
    private const MAX_TRACE_FRAMES = 10;

    /**
     * The bitmask of error levels to capture and forward.
     *
     * @var int
     */
    private int $levels;

    /**
     * The HTTP client used to dispatch entries.
     *
     * @var Client
     */
    private Client $client;

    /**
     * The current session token.
     *
     * @var string
     */
    private string $session;

    /**
     * The request lifecycle ID generated by Debug::init().
     *
     * @var string
     */
    private string $requestId;

    /**
     * Absolute path to the DebugPHP package source directory.
     * Used to strip internal frames from the captured backtrace.
     *
     * @var string
     */
    private string $packageDir;

    /**
     * Registers the error handler and shutdown function.
     *
     * @param int    $levels    Bitmask of PHP error levels to capture (e.g. E_ALL, E_WARNING | E_NOTICE).
     * @param Client $client    The HTTP client instance from Debug.
     * @param string $session   The session token from Debug.
     * @param string $requestId The request lifecycle ID from Debug::init().
     */
    public function __construct(int $levels, Client $client, string $session, string $requestId)
    {
        $this->levels     = $levels;
        $this->client     = $client;
        $this->session    = $session;
        $this->requestId  = $requestId;
        $this->packageDir = dirname(__DIR__) . '/src';

        $this->registerErrorHandler();
        $this->registerShutdownHandler();
    }

    /**
     * Registers a custom error handler for non-fatal PHP errors.
     *
     */
    private function registerErrorHandler(): void
    {
        set_error_handler(
            function (int $errno, string $errstr, string $errfile, int $errline): bool {
                $this->forward($errno, $errstr, $errfile, $errline, debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS));
                return true;
            },
            $this->levels,
        );
    }

    /**
     * Registers a shutdown function to capture fatal errors.
     *
     * Fatal error types (E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR)
     * cannot be intercepted by set_error_handler() and are handled here
     * via error_get_last(). No backtrace is available for fatal errors.
     */
    private function registerShutdownHandler(): void
    {
        register_shutdown_function(function (): void {
            $error = error_get_last();

            if ($error === null) {
                return;
            }

            $type = $error['type'];

            if (!in_array($type, self::FATAL_TYPES, true)) {
                return;
            }

            if (!($type & $this->levels)) {
                return;
            }

            $this->forward($type, $error['message'], $error['file'], $error['line'], []);
        });
    }

    /**
     * Builds a structured table entry and dispatches it to the dashboard.
     *
     * @param int                  $errno   The PHP error level constant (e.g. E_WARNING).
     * @param string               $errstr  The error message.
     * @param string               $errfile The absolute path of the file where the error occurred.
     * @param int                  $errline The line number where the error occurred.
     * @param array<int, mixed>    $trace   The raw backtrace from debug_backtrace().
     */
    private function forward(int $errno, string $errstr, string $errfile, int $errline, array $trace): void
    {
        $levelName = $this->resolveLevelName($errno);

        /** @var list<array<string, string>> $rows */
        $rows = [
            ['Property' => 'Message', 'Value' => $errstr],
            ['Property' => 'File',    'Value' => basename($errfile) . ' : line ' . $errline],
            ['Property' => 'Path',    'Value' => $errfile],
            ['Property' => '--- Stack Trace ---', 'Value' => ''],
        ];

        $traceRows = $this->buildTraceRows($trace);

        if ($traceRows === []) {
            $rows[] = ['Property' => '#', 'Value' => 'No trace available (fatal error)'];
        } else {
            foreach ($traceRows as $row) {
                $rows[] = $row;
            }
        }

        /** @var array{headers: list<string>, rows: list<array<string, string>>} $data */
        $data = [
            'headers' => ['Property', 'Value'],
            'rows'    => $rows,
        ];

        $entry = new Entry($this->client, $this->session, $this->requestId, $data, 'PHP ' . $levelName);
        $entry->type('table')->color($this->resolveColor($errno));
    }

    /**
     * Builds the trace rows from a raw backtrace array.
     *
     * Filters out:
     *   - Frames with no file (internal PHP/extension calls).
     *   - Frames originating inside the DebugPHP package directory.
     *
     * Caps the result at {@see MAX_TRACE_FRAMES} to avoid flooding the dashboard.
     *
     * @param array<int, mixed> $trace The raw output of debug_backtrace().
     *
     * @return list<array<string, string>> Rows ready to append to the table payload.
     */
    private function buildTraceRows(array $trace): array
    {
        $rows  = [];
        $index = 0;

        foreach ($trace as $frame) {
            if (!is_array($frame)) {
                continue;
            }

            $file = isset($frame['file']) && is_string($frame['file']) ? $frame['file'] : '';

            if ($file === '') {
                continue;
            }

            if (str_starts_with($file, $this->packageDir)) {
                continue;
            }

            $line     = isset($frame['line']) && is_int($frame['line']) ? $frame['line'] : 0;
            $function = isset($frame['function']) && is_string($frame['function']) ? $frame['function'] : '';
            $class    = isset($frame['class'])    && is_string($frame['class'])    ? $frame['class']    : '';
            $type     = isset($frame['type'])     && is_string($frame['type'])     ? $frame['type']     : '';

            $call = $class !== '' ? $class . $type . $function . '()' : ($function !== '' ? $function . '()' : '');

            $value = basename($file) . ' : line ' . $line;
            if ($call !== '') {
                $value .= ' → ' . $call;
            }

            $rows[] = [
                'Property' => '#' . $index,
                'Value'    => $value,
            ];

            $index++;

            if ($index >= self::MAX_TRACE_FRAMES) {
                $remaining = count($trace) - $index;
                if ($remaining > 0) {
                    $rows[] = [
                        'Property' => '...',
                        'Value'    => $remaining . ' more frame(s) omitted',
                    ];
                }
                break;
            }
        }

        return $rows;
    }

    /**
     * Resolves a human-readable name for a PHP error level constant.
     *
     * @param int $errno The PHP error level constant.
     *
     * @return string The constant name (e.g. "E_WARNING").
     */
    private function resolveLevelName(int $errno): string
    {
        return match (true) {
            (bool) ($errno & E_ERROR)           => 'E_ERROR',
            (bool) ($errno & E_WARNING)         => 'E_WARNING',
            (bool) ($errno & E_PARSE)           => 'E_PARSE',
            (bool) ($errno & E_NOTICE)          => 'E_NOTICE',
            (bool) ($errno & E_CORE_ERROR)      => 'E_CORE_ERROR',
            (bool) ($errno & E_CORE_WARNING)    => 'E_CORE_WARNING',
            (bool) ($errno & E_COMPILE_ERROR)   => 'E_COMPILE_ERROR',
            (bool) ($errno & E_USER_ERROR)      => 'E_USER_ERROR',
            (bool) ($errno & E_USER_WARNING)    => 'E_USER_WARNING',
            (bool) ($errno & E_USER_NOTICE)     => 'E_USER_NOTICE',
            (bool) ($errno & E_DEPRECATED)      => 'E_DEPRECATED',
            (bool) ($errno & E_USER_DEPRECATED) => 'E_USER_DEPRECATED',
            default                             => 'E_UNKNOWN',
        };
    }

    /**
     * Maps a PHP error level constant to a dashboard color.
     *
     * @param int $errno The PHP error level constant.
     *
     * @return string A valid dashboard color name.
     */
    private function resolveColor(int $errno): string
    {
        $isFatal   = (bool) ($errno & (E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR));
        $isWarning = (bool) ($errno & (E_WARNING | E_CORE_WARNING | E_COMPILE_WARNING | E_USER_WARNING));
        $isNotice  = (bool) ($errno & (E_NOTICE | E_USER_NOTICE));

        return match (true) {
            $isFatal   => 'red',
            $isWarning => 'orange',
            $isNotice  => 'blue',
            default    => 'purple',
        };
    }
}
